# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-23 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import menus.models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to=menus.models.image_upload_to),
        ),
    ]
